name: Generate Image Data

on:
  push:
    branches:
      - main  # 触发工作流的分支

jobs:
  build:
    runs-on: ubuntu-latest

    # 授予工作流向仓库写入内容的权限
    permissions:
      contents: write

    steps:
      # 步骤 1: 拉取最新的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤 2: 设置 Python 3.10 环境
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # =======================================================
      #  ▼▼▼ 在这里添加了安装依赖的步骤 ▼▼▼
      # =======================================================
      - name: Install dependencies
        run: pip install Pillow
      # =======================================================

      # 步骤 3: 运行 Python 脚本生成数据文件
      - name: Run script to generate image list
        run: python ./generate_list.py

      # 步骤 4: 如果数据文件有变化，则自动提交并推送
      - name: Commit and push if changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: auto-generate image data'
          file_pattern: data/image-data.json
          commit_user_name: 'GitHub Actions Bot'
          commit_user_email: 'actions@github.com'
          commit_author: 'GitHub Actions Bot <actions@github.com>'
